# Generated by Django 5.2.4 on 2025-07-15 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="githubauth",
            name="user",
        ),
        migrations.RemoveField(
            model_name="googletoken",
            name="user",
        ),
        migrations.RemoveField(
            model_name="users",
            name="user",
        ),
        migrations.DeleteModel(
            name="AppsAuthentication",
        ),
        migrations.DeleteModel(
            name="GitHubAuth",
        ),
        migrations.DeleteModel(
            name="GoogleToken",
        ),
        migrations.DeleteModel(
            name="Users",
        ),
    ]
