# Generated by Django 5.2.4 on 2025-07-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_users_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='telegram_id',
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
    ]
