# Generated by Django 5.2.4 on 2025-07-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_users_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
