# Generated by Django 5.2.4 on 2025-07-26 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_users_telegram_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='telegram_id',
            new_name='telegram_user_id',
        ),
    ]
