# Generated by Django 5.2.4 on 2025-07-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_users_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='users',
            name='coins',
        ),
        migrations.DeleteModel(
            name='AppsAuthentication',
        ),
        migrations.DeleteModel(
            name='LoginHistory',
        ),
    ]
