# Generated by Django 5.2.4 on 2025-07-30 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_remove_loginhistory_user_remove_users_coins_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="googletoken",
            name="user",
        ),
        migrations.DeleteModel(
            name="GitHubAuth",
        ),
        migrations.DeleteModel(
            name="GoogleToken",
        ),
    ]
