# Generated by Django 5.2.4 on 2025-07-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_remove_googletoken_user_delete_githubauth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="balance",
            field=models.BigIntegerField(default=0),
        ),
    ]
