# Generated by Django 5.2.4 on 2025-07-31 13:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0011_users_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubAuth",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=50, null=True)),
                ("access_token", models.TextField(blank=True, null=True)),
                ("user_github_id", models.BigIntegerField(blank=True, null=True)),
                ("avatar_url", models.URLField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.users",
                    ),
                ),
            ],
            options={
                "db_table": "GitHubAuth",
            },
        ),
        migrations.CreateModel(
            name="GoogleToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                ("sub", models.CharField(default=0, max_length=50)),
                ("expires_in", models.BigIntegerField(default=3599)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.users",
                    ),
                ),
            ],
            options={
                "db_table": "GoogleToken",
            },
        ),
    ]
