# Generated by Django 5.2.4 on 2025-07-31 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_githubauth_googletoken"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GoogleToken",
            new_name="GoogleAuth",
        ),
        migrations.AlterModelTable(
            name="googleauth",
            table="GoogleAuth",
        ),
    ]
