# Generated by Django 5.2.4 on 2025-08-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0013_rename_googletoken_googleauth_alter_googleauth_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="actived_account",
            field=models.BooleanField(default=False),
        ),
    ]
